[project]
name = "feed-broadcast"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.feed-broadcast-core]
path = "contracts/feed-broadcast-core.clar"
depends_on = []

[contracts.feed-broadcast-market]
path = "contracts/feed-broadcast-market.clar"
depends_on = []

[contracts.feed-broadcast-social]
path = "contracts/feed-broadcast-social.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
